services:
  - type: web
    name: n8n-ai-agent
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_API_BASE
        value: https://api.openai.com/v1

