runtime: python311

env_variables:
  FLASK_ENV: production
  PYTHONPATH: /srv

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

handlers:
- url: /static
  static_dir: src/static
  
- url: /.*
  script: auto
  secure: always

